// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeBVw0ME73Srpxt2qXAvA1PD4IV0gXgV0',
    appId: '1:117375448139:web:71c607aa77da2b63fec9ce',
    messagingSenderId: '117375448139',
    projectId: 'flutterdojo-2022',
    authDomain: 'flutterdojo-2022.firebaseapp.com',
    storageBucket: 'flutterdojo-2022.appspot.com',
    measurementId: 'G-L10G2741WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHiCC_9ML8DpNaA5g_o1K6LFWCBMJuGsI',
    appId: '1:117375448139:android:cabac58bf49f164cfec9ce',
    messagingSenderId: '117375448139',
    projectId: 'flutterdojo-2022',
    storageBucket: 'flutterdojo-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Fce_M0fnZKmfalKTe3gKWmDSMD43ldM',
    appId: '1:117375448139:ios:013068c03bda533ffec9ce',
    messagingSenderId: '117375448139',
    projectId: 'flutterdojo-2022',
    storageBucket: 'flutterdojo-2022.appspot.com',
    iosClientId: '117375448139-51vqrrotbb8d32jn9bldjfj4tta2bpjn.apps.googleusercontent.com',
    iosBundleId: 'dev.gdifrancesco.flutterDojo2022',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Fce_M0fnZKmfalKTe3gKWmDSMD43ldM',
    appId: '1:117375448139:ios:013068c03bda533ffec9ce',
    messagingSenderId: '117375448139',
    projectId: 'flutterdojo-2022',
    storageBucket: 'flutterdojo-2022.appspot.com',
    iosClientId: '117375448139-51vqrrotbb8d32jn9bldjfj4tta2bpjn.apps.googleusercontent.com',
    iosBundleId: 'dev.gdifrancesco.flutterDojo2022',
  );
}
